clean

diff --git a/.github/workflows/main-branch-only.yml b/.github/workflows/main-branch-only.yml
--- a/.github/workflows/main-branch-only.yml
+++ b/.github/workflows/main-branch-only.yml
@@ -40,13 +40,12 @@ jobs:
           echo "current-context:" $(kubectl config current-context)
           for i in {1..3}; do
             kubectl apply -f deploy/deploy.yaml
-            kubectl rollout status deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system --timeout=240s
-            if [ $? -eq 0 ]; then
+            if kubectl rollout status deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system --timeout=240s; then
               break
-            else
-              echo "Rollout status check failed, retrying in 20 seconds..."
-              sleep 20
             fi
+            [ $i -eq 3 ] && exit 1
+            echo "Rollout status check failed, retrying in 20 seconds..."
+            sleep 20
           done
           kubectl get crd | grep eventbrokers
 
@@ -64,13 +63,12 @@ jobs:
           kubectl apply -f developer.yaml | grep "test-broker created"
           sleep 25 ; kubectl get all
           for i in {1..3}; do
-            kubectl wait pods --selector app.kubernetes.io/instance=test-broker --for condition=Ready --timeout=300s
-            if [ $? -eq 0 ]; then
+            if kubectl wait pods --selector app.kubernetes.io/instance=test-broker --for condition=Ready --timeout=300s; then
               break
-            else
-              echo "Waiting for pods failed, retrying in 15 seconds..."
-              sleep 15
             fi
+            [ $i -eq 3 ] && exit 1
+            echo "Waiting for pods failed, retrying in 15 seconds..."
+            sleep 15
           done
           kubectl get po --show-labels | grep test-broker | grep "1/1"
           kubectl get po --show-labels | grep test-broker | grep active=true
@@ -86,3 +84,4 @@ jobs:
         run: |
           kubectl delete eventbroker test-broker --ignore-not-found | grep deleted || true
           kubectl delete ns $TESTNAMESPACE --ignore-not-found
+          kubectl delete -f deploy/deploy.yaml --ignore-not-found
